In [6]:
import numpy as np, argparse, time, pickle, random
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler
from dataloader import IEMOCAPDataset

In [7]:
def get_train_valid_sampler(trainset, valid=0.1):
    size = len(trainset)
    idx = list(range(size))
    split = int(valid*size)
    return SubsetRandomSampler(idx[split:]), SubsetRandomSampler(idx[:split])

In [8]:
def get_IEMOCAP_loaders(batch_size=32, valid=0.1, num_workers=0, pin_memory=False):
    trainset = IEMOCAPDataset()
    train_sampler, valid_sampler = get_train_valid_sampler(trainset, valid)

    train_loader = DataLoader(trainset,
                              batch_size=batch_size,
                              sampler=train_sampler,
                              collate_fn=trainset.collate_fn,
                              num_workers=num_workers,
                              pin_memory=pin_memory)

    valid_loader = DataLoader(trainset,
                              batch_size=batch_size,
                              sampler=valid_sampler,
                              collate_fn=trainset.collate_fn,
                              num_workers=num_workers,
                              pin_memory=pin_memory)

    testset = IEMOCAPDataset(train=False)
    test_loader = DataLoader(testset,
                             batch_size=batch_size,
                             collate_fn=testset.collate_fn,
                             num_workers=num_workers,
                             pin_memory=pin_memory)

    return train_loader, valid_loader, test_loader

In [14]:
train_loader, valid_loader, test_loader = get_IEMOCAP_loaders(valid=0.0, batch_size=32)

In [72]:
trainset = IEMOCAPDataset()
testset = IEMOCAPDataset(train=False)

31

In [69]:
trainset[0][0].shape

torch.Size([30, 100])

In [26]:
trainset[0][1].shape

torch.Size([30, 512])

In [25]:
trainset[0][2].shape

torch.Size([30, 100])

In [63]:
trainset[0][3]

tensor([[1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.]])

In [62]:
trainset[0][4]

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
trainset[0][5]   # [1]*len(self.videoLabels[vid])

tensor([2, 1, 4, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0])

In [32]:
trainset[0][6] # self.keys

'Ses02F_script01_3'

In [34]:
len(trainset)

120

In [84]:
trainset[3][5]

tensor([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 0, 4, 4, 4, 4, 4, 4, 4, 0,
        0, 4, 0, 0, 4, 4, 0, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 4, 0, 4,
        4, 4, 0, 4, 0])

In [ ]:
trainset[:][0] # text features of all utternnaces in the dialogue
trainset[:][5] # label of all utterances

In [85]:
trainset[0][0]

tensor([[-12.1891,  -8.2596,  -9.6170,  ...,   9.7945,   3.6077,   9.0825],
        [ -1.4376,  10.2238,   8.5770,  ...,   2.2476,  -4.2998, -11.3337],
        [  7.8908,  -6.7292,  13.9702,  ...,  14.6724, -10.4947,  -9.4663],
        ...,
        [  8.6563,  -4.5784,  -1.2025,  ...,   9.5165,  12.0909, -18.2481],
        [ -0.5963,  21.4521, -11.9296,  ...,   2.9743,  14.5117,  -6.4756],
        [ -7.4868, -24.3850,   1.6967,  ...,  14.9915,   0.3419, -10.8545]])